Imtec 356 sahi yolov8
sporttotal-tv/st-ultralytics pull request #3
Opened 2024-03-13 09:58 UTC by pradip-sttv

Add scripts to support:
1. Yolov8 inference on input video and dump final detections in .bbox format
2. Sahi+Yolov8 inference on input video and dump final detections in .bbox format. 
3. Also added support for frame level detection visualisation and final video generation.

2024-03-13 10:21 UTC, daniel-andrade-st reviewed
I see there is a lot of overlap between inference_sahi.py and inference_yolov8.py, including the functions names themselves, which can be a bit confusing.
If this is for more than a POC, it would be great to refactor it a bit further :)

2024-03-13 10:21 UTC, daniel-andrade-st commented on scripts/inference_sahi.py
> +            slice_height=512,
I would have these hardcoded argument values in the config file, as it will be useful to experiment for different values in the future, particularly for ball or puck.

2024-03-13 10:21 UTC, daniel-andrade-st commented on requirements_sahi.txt
Do we need a separate requirements file just for SAHI?

2024-03-13 12:05 UTC, nghorbani requested changes

2024-03-13 12:05 UTC, nghorbani commented on scripts/inference_sahi.py
> +            if out_path is not None:
you could use video writer from st-commons. it is optional

2024-03-13 12:05 UTC, nghorbani commented on scripts/inference_sahi.py
> +        if video_writer is not None:
VideoWriter of st-commons will automatically close the video file

2024-03-13 12:05 UTC, nghorbani commented on scripts/inference_yolov8.py
> +def visualise_detections(frame_image,
could you reuse visualize detections of inference_sahi?

2024-03-13 12:05 UTC, nghorbani commented on scripts/inference_yolov8.py
> +        model_path: Path to the custom-trained model weights (default: "yolov8n.pt").
read model_path from the config file. e.g. conf.yaml should have these configurations: yolov8: ${support_base_dir}/yolov8/yolob8.pt

2024-03-14 14:33 UTC, pradip-sttv commented on scripts/inference_sahi.py
> +            slice_height=512,
Moved all hyper-parameters to config.yaml file.

2024-03-14 14:36 UTC, pradip-sttv commented on scripts/inference_yolov8.py
> +def visualise_detections(frame_image,
Moved both modes into one file and added 'sahi_inference' as flag to enable sahi usage.

2024-03-14 15:16 UTC, pradip-sttv commented on scripts/inference_yolov8.py
> +        model_path: Path to the custom-trained model weights (default: "yolov8n.pt").
Added support to read model_path from config if not passed directly.

2024-04-02 13:04 UTC, closed without merging